Proxy:
  Port: 8080
  TLS:
    Certificate: # Certificate to User
    Key: # Certificate Key to User
LDAP:
  URL: ldap://localhost
  Group: readers
  OuBase: ou
#  SearchGroupFilter: (&(cn=%s)(objectClass=posixGroup))
  BaseDN: dc=example,dc=com
  BindDN: cn=admin,dc=example,dc=com 
  # cn=users,
Kubernetes:
  Host: api.k3s.example.com:6443
#  KubeConfig:
#  Namespace: