---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-auth-proxy
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/approval
  verbs:
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - signers
  resourceNames:
  - kubernetes.io/kube-apiserver-client
  verbs:
  - approve
- apiGroups:
  - ""
  resources:
  - secrets
  - endpoints
  verbs:
  - create
  - get
  - list
  - watch
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-auth-proxy
  namespace: kube-auth-proxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-auth-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-auth-proxy
subjects:
- kind: ServiceAccount
  name: kube-auth-proxy
  namespace: kube-auth-proxy