apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testrole
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testrole
subjects:
- kind: User
  name: testuser
  apiGroup: rbac.authorization.k8s.io